server:
  port: 8889
  
spring:
  application:
    name: configclient
    
management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    org.springframework.cloud: 'TRACE'
welcome:  
    client:  
      message: welcome
      user: Prod
      password: '{cipher}b9acf13af9c3318642c4436ca22720665fa4c5dbae2d2262a5f0c2c58540e9a3'
  