server:
  port: 8889

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true
  endpoint:
    env:
      post:
        enabled: true
    shutdown:
      enabled: true
      
logging:
  level:
    org.springframework.cloud: 'TRACE'
welcome:  
    client:  
      message: welcome
      user: Dev
      password: pass
      #encryptedPassword: '{cipher}682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda'
  